### ISSUE TITLE
 Censys is not a constructor

### ISSUE THREAD

**Issue by kullu208025** [b4dnewz/node-censys#3]
const instance =new  Censys({
   apiID :  xxxxx,
   apiSecert : xxxxx
});
Above code is showing following error:
uncaughtException: Censys is not a constructor\nTypeError: Censys is not a constructor\n

**Comment by b4dnewz** [comment]
how do you import it? 
can you show all the code that you are running and the version that you are using?

**Comment by kullu208025** [comment]
Hi @b4dnewz 
var Censys = require('censys.io');

const instance =new Censys({
   apiID :  "3d6xxxxxxxxxxxxxxxxxxxx",
   apiSecert : "kfOxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
});

I am working in nodejs!!

**Comment by b4dnewz** [comment]
the problem is here `var Censys = require('censys.io');`

Since the module is typescript based you should use __import__ statement as shown in the project readme or requiring the default export if using node require.
```js
var Censys = require('censys.io').default;
```

Check [this SO answer](https://stackoverflow.com/questions/55940063/why-does-using-typescript-class-in-javascript-require-default?answertab=active#tab-top) for some background informations about this
